#!/usr/bin/env bash

NODE_ENV=production node ./support/app &
pid=$!

bench() {
  ab -n 5000 -c 50 -k -q http://127.0.0.1:8000$1 \
    | grep "Requests per" \
    | cut -d ' ' -f 7 \
    | xargs echo "$2:"
}

bench_conditional() {
  ab -n 5000 -c 50 -H "If-None-Match: $3" -k -q http://127.0.0.1:8000$1 \
    | grep "Requests per" \
    | cut -d ' ' -f 7 \
    | xargs echo "$2:"
}

sleep .5
bench / "Hello World"
bench /blog "Mounted Hello World"
bench /middleware "Middleware"
bench /match "Router"
bench /render "Render"
bench /json "JSON tiny"
bench /json/small "JSON small"
bench /json/large "JSON large"
bench_conditional /json/large "JSON large etag" -1355435680

# 1.25 mb/s

kill -9 $pid